# Generated by Django 5.1.1 on 2024-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_autor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='Patronymic'),
        ),
    ]
