# Generated by Django 5.1.1 on 2024-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_profile_user_patronymic_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Image'),
        ),
    ]
