# Generated by Django 5.1.3 on 2025-01-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(blank=True, null=True, verbose_name="Image_url"),
        ),
    ]
